# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-dash" do
  version "0.0.8"

  on_macos do
    on_intel do
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_darwin-amd64"
      sha256 "6155de054247883fde0285585a796ba85207d9bc6dfb2bfc5e68968a5fa9a939"
      binary "docker-dash_v0.0.8_darwin-amd64", target: "docker-dash"
    end
    on_arm do
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_darwin-arm64"
      sha256 "dc26dc4aeb71bccf9ac765fd0f821533eb158b0fad0fbb2e7c2e3d12bc6c87a4"
      binary "docker-dash_v0.0.8_darwin-arm64", target: "docker-dash"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_linux-amd64"
      sha256 "647ac5d2bce68c4618383291397df5b6e91be2fc12feaa49a30dc0c3d343b427"
      binary "docker-dash_v0.0.8_linux-amd64", target: "docker-dash"
    end
    on_arm do
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_linux-arm64"
      sha256 "ea9e4fa83a59d77a3be446a9ea9df9f3053d2cf8054643007cab16f60c4054fa"
      binary "docker-dash_v0.0.8_linux-arm64", target: "docker-dash"
    end
  end

  name "docker-dash"
  desc "Terminal UI dashboard for managing Docker containers, images, volumes, and networks"
  homepage "https://github.com/GustavoCaso/docker-dash"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
