# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-dash" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "17984ecd15f0767460c4fef016cc573b9cd2a4184246c03beeecb5c3d4a64f66"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_darwin-amd64"
      binary "docker-dash_v0.1.0_darwin-amd64", target: "docker-dash"
    end
    on_arm do
      sha256 "ad7c501ddded7d66ee86f596ad585a73e63b32e3ca18fae7a5892fa9da8c5e67"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_darwin-arm64"
      binary "docker-dash_v0.1.0_darwin-arm64", target: "docker-dash"
    end
  end

  on_linux do
    on_intel do
      sha256 "e43cdd9bd609e497204b8baba169fcaf86522227a4d00d43ea61fad583afa992"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_linux-amd64"
      binary "docker-dash_v0.1.0_linux-amd64", target: "docker-dash"
    end
    on_arm do
      sha256 "b99ef317e0da8a47c8b47c74b75ffa9731e002178ad77d22f1c3edbbd9c4172d"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_linux-arm64"
      binary "docker-dash_v0.1.0_linux-arm64", target: "docker-dash"
    end
  end

  name "docker-dash"
  desc "Terminal UI dashboard for managing Docker containers, images, volumes, and networks"
  homepage "https://github.com/GustavoCaso/docker-dash"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary_name = Hardware::CPU.arm? ? "docker-dash_v#{version}_darwin-arm64" : "docker-dash_v#{version}_darwin-amd64"
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

end
