# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-dash" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "62f039ec0ef394aa657bc420a5117eac742f900ee8929afef6c73eac194dfa5a"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_darwin-amd64"
      binary "docker-dash_v0.1.2_darwin-amd64", target: "docker-dash"
    end
    on_arm do
      sha256 "9587d40258fea92c5ea192b8b536032b213e8e5c52ba6c336c1802fd104292cc"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_darwin-arm64"
      binary "docker-dash_v0.1.2_darwin-arm64", target: "docker-dash"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7a824cc4c4d82d2e5cd9b79ba27a13a2f7726783af1194e902bf38b8b9f00fe"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_linux-amd64"
      binary "docker-dash_v0.1.2_linux-amd64", target: "docker-dash"
    end
    on_arm do
      sha256 "cc6d311f643ff0290933c7303ff6a8d4b266cea8ed4c1bffa5d6ec93f9f4d046"
      url "https://github.com/GustavoCaso/docker-dash/releases/download/v#{version}/docker-dash_v#{version}_linux-arm64"
      binary "docker-dash_v0.1.2_linux-arm64", target: "docker-dash"
    end
  end

  name "docker-dash"
  desc "Terminal UI dashboard for managing Docker containers, images, volumes, and networks"
  homepage "https://github.com/GustavoCaso/docker-dash"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary_name = Hardware::CPU.arm? ? "docker-dash_v#{version}_darwin-arm64" : "docker-dash_v#{version}_darwin-amd64"
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

end
