# This file was generated by GoReleaser. DO NOT EDIT.
cask "meeseeks" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "b1896d6a5c531b390748e6f1630b72f25a0262410100814b64515f2c2a5a10cc"
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_darwin-amd64"
      binary "meeseeks_v0.1.3_darwin-amd64", target: "meeseeks"
    end
    on_arm do
      sha256 "31f8db927f9181fd87ed448e834942569bfb874594028f01dbc82542e9612641"
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_darwin-arm64"
      binary "meeseeks_v0.1.3_darwin-arm64", target: "meeseeks"
    end
  end

  name "meeseeks"
  desc "A simple and lightweight process manager for Go applications and CLI tool that simplify managing background processes"
  homepage "https://github.com/GustavoCaso/meeseeks"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
