# This file was generated by GoReleaser. DO NOT EDIT.
cask "meeseeks" do
  name "meeseeks"
  desc "A simple and lightweight process manager for Go applications and CLI tool that simplify managing background processes"
  homepage "https://github.com/GustavoCaso/meeseeks"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    on_intel do
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_darwin-amd64"
      sha256 "b748a0eb5290ba2f6cae498f2f1c899daef9bfab0ef41595ec8a7f43a3ab3c85"
      binary "meeseeks_v0.1.2_darwin-amd64", target: "meeseeks"
    end
    on_arm do
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_darwin-arm64"
      sha256 "4f64741831f9c8c9b18f06e3771f290aecfa08afa50b331ebc0b436aef5b76dd"
      binary "meeseeks_v0.1.2_darwin-arm64", target: "meeseeks"
    end
  end

  # No zap stanza required
end
