# This file was generated by GoReleaser. DO NOT EDIT.
cask "meeseeks" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "5cf882b6c76655a93d7b1ac01663e8f368f97b1244aa007f74be6c41236778ab"
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_darwin-amd64"
      binary "meeseeks_v0.2.0_darwin-amd64", target: "meeseeks"
    end
    on_arm do
      sha256 "b0a63620931f91b2a806b9319772f1d8c073204d48b73dc27a530321c3d92efa"
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_darwin-arm64"
      binary "meeseeks_v0.2.0_darwin-arm64", target: "meeseeks"
    end
  end

  on_linux do
    on_intel do
      sha256 "683e54d972797b36f70a7b8a654f500c2a13ef3f4501a96be93aad2faffd4c45"
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_linux-amd64"
      binary "meeseeks_v0.2.0_linux-amd64", target: "meeseeks"
    end
    on_arm do
      sha256 "f246187a9dce0643dc522b99e0e260d0a9f9fb78f53131c214e306b33c2d7c27"
      url "https://github.com/GustavoCaso/meeseeks/releases/download/v#{version}/meeseeks_v#{version}_linux-arm64"
      binary "meeseeks_v0.2.0_linux-arm64", target: "meeseeks"
    end
  end

  name "meeseeks"
  desc "A simple and lightweight process manager for Go applications and CLI tool that simplify managing background processes"
  homepage "https://github.com/GustavoCaso/meeseeks"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary_name = Hardware::CPU.arm? ? "meeseeks_v#{version}_darwin-arm64" : "meeseeks_v#{version}_darwin-amd64"
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
    end
  end

  # No zap stanza required

end
